### ISSUE TITLE
getting error in macOS / OF github

### ISSUE THREAD

**Issue by moebiussurfing** [nariakiiwatani/ofxWatchFile#1]
Error:(9, 7) virtual function 'reload' has a different return type ('void') than the function it overrides (which has return type 'bool')
any tips around?

**Comment by moebiussurfing** [comment]
sorry, it's solved replacing void to bool:
```
class AutoReloadImage : public ofxWatchFile, public ofImage
{
private:
	bool reload(ofFile &file) {
		ofImage::load(file.path());
	}
};
```

**Comment by nariakiiwatani** [comment]
nice. :)

**Comment by nariakiiwatani** [comment]
But be careful, you should return a bool value within reload.
