### ISSUE TITLE
reload made const -> changes existing classes behaviour

### ISSUE THREAD

**Issue by artificiel** [nariakiiwatani/ofxWatchFile#2]
hello! commit 19959a195e8c38bec34c5869e705267ec7b6e38e added `const` to the virtual `reload()` method. classes inheriting ofxWatchFile and overriding the non-const `reload()` (original) method stop working. (for example, the little derived class  example in the README will not work).

what is the reason for this change? (current case, overriding method is not designed to be const so simply adding `const` is not a direct solution to conform to the new more restrictive behaviour).

[edit: I am not worried about new design/implementation (can work with const), but breakage of existing code that otherwise fails silently (if not using `override` to get warnings, the method just stops doing anything)]

**Comment by nariakiiwatani** [comment]
hello!
I don't remember why but seems strange.
will give it a look.
thanks!

**Comment by nariakiiwatani** [comment]
I think it's my fault so removed.
149ee3d35ac34076186e41554764ff46f4e7ffc0

Thanks again!

**Comment by artificiel** [comment]
ok super! thanks
